ENV['treatment_arm_DOCKER_HOSTNAME'] = 'localhost' #'192.168.99.100'
ENV['patient_state_DOCKER_HOSTNAME'] = 'localhost'
ENV['treatment_arm_api_PORT'] = '10235'
ENV['patient_state_PORT'] = '10236'
ENV['protocol'] = 'http'