require_relative '../ion_message_loader'
require_relative '../patient_message_loader'

# IonMessageLoader.upload_start_with_wait_time(0.5)
# IonMessageLoader.create_ion_reporter('mda')
# IonMessageLoader.create_ion_reporter('mda')
# IonMessageLoader.create_ion_reporter('mda')
# IonMessageLoader.create_ion_reporter('mda')
# IonMessageLoader.create_ion_reporter('mda')
# IonMessageLoader.create_ion_reporter('mda')
# IonMessageLoader.create_ion_reporter('mda')
# IonMessageLoader.create_ion_reporter('mda')
# IonMessageLoader.create_ion_reporter('mocha')
# IonMessageLoader.create_ion_reporter('mocha')
# IonMessageLoader.create_ion_reporter('mocha')
# IonMessageLoader.create_ion_reporter('mocha')
# IonMessageLoader.create_ion_reporter('mocha')
# IonMessageLoader.create_ion_reporter('mocha')
# IonMessageLoader.create_ion_reporter('mocha')
#
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'no_template')
# IonMessageLoader.create_sample_control('mocha', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
#
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'positive')
# IonMessageLoader.create_sample_control('mocha', 'no_template')
# IonMessageLoader.create_sample_control('mocha', 'no_template')
# IonMessageLoader.create_sample_control('mocha', 'no_template')
# IonMessageLoader.create_sample_control('mocha', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'no_template')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
# IonMessageLoader.upload_done


IonMessageLoader.upload_start_with_wait_time(60)

IonMessageLoader.create_variant_report('SC_SA1CB', 'sc_update_data.json')
IonMessageLoader.create_variant_report('SC_YQ111', 'sc_update_data_no_template_falsePositive.json')
IonMessageLoader.create_variant_report('SC_KGPVI', 'sc_update_data_no_template_passed.json')
IonMessageLoader.create_variant_report('SC_67VKV', 'sc_update_data_positive_failed.json')
IonMessageLoader.create_variant_report('SC_5AMCC', 'sc_update_data_positive_passed.json')
IonMessageLoader.create_variant_report('SC_PALFC', 'sc_update_data_positive_falsePositive.json')
IonMessageLoader.create_variant_report('SC_FDK09', 'sc_update_data_proficiency.json')
IonMessageLoader.create_variant_report('SC_LGU30', 'sc_update_data_proficiency_germline_filter.json')
IonMessageLoader.create_variant_report('SC_BAXXY', 'sc_update_data_proficiency_nopass_filter.json')
IonMessageLoader.upload_done