require_relative '../ion_message_loader'
require_relative '../patient_message_loader'

IonMessageLoader.upload_start_with_wait_time(0.5)
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')

IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'no_template')
IonMessageLoader.create_sample_control('mocha', 'proficiency_competency')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')

IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'no_template')
IonMessageLoader.create_sample_control('mocha', 'no_template')
IonMessageLoader.create_sample_control('mocha', 'no_template')
IonMessageLoader.create_sample_control('mocha', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')


IonMessageLoader.upload_done