require_relative '../ion_message_loader'
require_relative '../patient_message_loader'


IonMessageLoader.upload_start_with_wait_time(0.5)
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mda')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')
IonMessageLoader.create_ion_reporter('mocha')

IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'positive')
IonMessageLoader.create_sample_control('mocha', 'no_template')
IonMessageLoader.create_sample_control('mocha', 'no_template')
IonMessageLoader.create_sample_control('mocha', 'no_template')
IonMessageLoader.create_sample_control('mocha', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'no_template')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')
IonMessageLoader.create_sample_control('mda', 'proficiency_competency')


IonMessageLoader.upload_done

PatientMessageLoader.upload_start_with_wait_time(15.0)
pt = PatientDataSet.new('ION_SC22_TsShipped')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)

pt = PatientDataSet.new('ION_SC43_TsShipped')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)

pt = PatientDataSet.new('ION_AQ02_TsShipped')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)

pt = PatientDataSet.new('ION_AQ03_BdShipped')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_blood(pt.id)
PatientMessageLoader.specimen_shipped_blood(pt.id, pt.bd_moi)

pt = PatientDataSet.new('ION_AQ04_TsShipped')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)

pt = PatientDataSet.new('ION_AQ23_TsShipped')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)

pt = PatientDataSet.new('ION_AQ24_TsShipped')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)

pt = PatientDataSet.new('ION_AQ80_TsShipped')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)

pt = PatientDataSet.new('ION_AQ81_TsShipped')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)

pt = PatientDataSet.new('ION_AQ41_TsVrUploaded')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)
PatientMessageLoader.variant_file_uploaded(pt.id, pt.moi, pt.ani)

pt = PatientDataSet.new('ION_AQ42_BdVrUploaded')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_blood(pt.id)
PatientMessageLoader.specimen_shipped_blood(pt.id, pt.bd_moi)
PatientMessageLoader.variant_file_uploaded(pt.id, pt.bd_moi, pt.ani)

pt = PatientDataSet.new('ION_AQ43_TsVrUploaded')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)
PatientMessageLoader.variant_file_uploaded(pt.id, pt.moi, pt.ani)

pt = PatientDataSet.new('ION_SF03_TsVrUploaded')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)
PatientMessageLoader.variant_file_uploaded(pt.id, pt.moi, pt.ani)

pt = PatientDataSet.new('ION_FL02_TsVrUploaded')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)
PatientMessageLoader.variant_file_uploaded(pt.id, pt.moi, pt.ani)

PatientMessageLoader.upload_done