require_relative '../patient_message_loader'

PatientMessageLoader.upload_start_with_wait_time(15)


pt = PatientDataSet.new('PT_PR13_VRConfirmedNoAssay')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)
PatientMessageLoader.tsv_vcf_uploaded(pt.id, pt.moi, pt.ani)
sleep(10.0)
PatientMessageLoader.variant_file_confirmed(pt.id, 'CONFIRMED', pt.moi, pt.ani)

pt = PatientDataSet.new('PT_PR13_AssayReceivedVRNotConfirmed')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)
PatientMessageLoader.specimen_shipped_slide(pt.id, pt.sei, pt.bc)
PatientMessageLoader.assay(pt.id, pt.sei, "POSITIVE", 'ICCPTENs', '2016-05-30T12:11:09.071-05:00')
PatientMessageLoader.assay(pt.id, pt.sei, "POSITIVE", 'ICCMLH1s', '2016-05-30T12:18:09.071-05:00')
PatientMessageLoader.tsv_vcf_uploaded(pt.id, pt.moi, pt.ani)

pt = PatientDataSet.new('PT_PR13_AssayAndVRDonePlanToY')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)
PatientMessageLoader.specimen_shipped_slide(pt.id, pt.sei, pt.bc)
PatientMessageLoader.assay(pt.id, pt.sei, "POSITIVE", 'ICCPTENs', '2016-05-30T12:11:09.071-05:00')
PatientMessageLoader.assay(pt.id, pt.sei, "POSITIVE", 'ICCMLH1s', '2016-05-30T12:18:09.071-05:00')
PatientMessageLoader.tsv_vcf_uploaded(pt.id, pt.moi, pt.ani)
sleep(10.0)
PatientMessageLoader.variant_file_confirmed(pt.id, 'CONFIRMED', pt.moi, pt.ani)

pt = PatientDataSet.new('PT_PR13_AssayAndVRDonePlanToN')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)
PatientMessageLoader.specimen_shipped_slide(pt.id, pt.sei, pt.bc)
PatientMessageLoader.assay(pt.id, pt.sei, "POSITIVE", 'ICCPTENs', '2016-05-30T12:11:09.071-05:00')
PatientMessageLoader.assay(pt.id, pt.sei, "POSITIVE", 'ICCMLH1s', '2016-05-30T12:18:09.071-05:00')
PatientMessageLoader.tsv_vcf_uploaded(pt.id, pt.moi, pt.ani)
sleep(10.0)
PatientMessageLoader.variant_file_confirmed(pt.id, 'CONFIRMED', pt.moi, pt.ani)

pt = PatientDataSet.new('PT_PR13_AssayAndVRDonePlanToU')
PatientMessageLoader.register_patient(pt.id)
PatientMessageLoader.specimen_received_tissue(pt.id, pt.sei)
PatientMessageLoader.specimen_shipped_tissue(pt.id, pt.sei, pt.moi)
PatientMessageLoader.specimen_shipped_slide(pt.id, pt.sei, pt.bc)
PatientMessageLoader.assay(pt.id, pt.sei, "POSITIVE", 'ICCPTENs', '2016-05-30T12:11:09.071-05:00')
PatientMessageLoader.assay(pt.id, pt.sei, "POSITIVE", 'ICCMLH1s', '2016-05-30T12:18:09.071-05:00')
PatientMessageLoader.tsv_vcf_uploaded(pt.id, pt.moi, pt.ani)
sleep(10.0)
PatientMessageLoader.variant_file_confirmed(pt.id, 'CONFIRMED', pt.moi, pt.ani)

PatientMessageLoader.upload_done
